"""empty message

Revision ID: bbe5653974c8
Revises: 
Create Date: 2020-05-15 15:45:06.609509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe5653974c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.drop_index('num', table_name='role')
    op.alter_column('user', 'account',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('user', 'passwd',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passwd',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
    op.alter_column('user', 'account',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.create_index('num', 'role', ['num'], unique=True)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
